package com.sapcework.memo.ui.theme

import androidx.compose.ui.graphics.Color

internal val lightPrimary = Color(0xFF1A73E8)
internal val lightOnPrimary = Color(0xFFFFFFFF)
internal val lightPrimaryContainer = Color(0xFFD3E3FD)
internal val lightOnPrimaryContainer = Color(0xFF001D35)
internal val lightSecondary = Color(0xFF565E71)
internal val lightOnSecondary = Color(0xFFFFFFFF)
internal val lightSecondaryContainer = Color(0xFFDAE2F9)
internal val lightOnSecondaryContainer = Color(0xFF131C2B)
internal val lightTertiary = Color(0xFF705575)
internal val lightOnTertiary = Color(0xFFFFFFFF)
internal val lightTertiaryContainer = Color(0xFFFAD8FD)
internal val lightOnTertiaryContainer = Color(0xFF28132E)
internal val lightError = Color(0xFFBA1A1A)
internal val lightOnError = Color(0xFFFFFFFF)
internal val lightErrorContainer = Color(0xFFFFDAD6)
internal val lightOnErrorContainer = Color(0xFF410002)
internal val lightBackground = Color(0xFFFDFCFF)
internal val lightOnBackground = Color(0xFF1A1C1E)
internal val lightSurface = Color(0xFFFDFCFF)
internal val lightOnSurface = Color(0xFF1A1C1E)
internal val lightSurfaceVariant = Color(0xFFE0E2EC)
internal val lightOnSurfaceVariant = Color(0xFF43474E)
internal val lightOutline = Color(0xFF73777F)

internal val darkPrimary = Color(0xFFA8C7FA)
internal val darkOnPrimary = Color(0xFF003258)
internal val darkPrimaryContainer = Color(0xFF00497D)
internal val darkOnPrimaryContainer = Color(0xFFD3E3FD)
internal val darkSecondary = Color(0xFFBEC6DC)
internal val darkOnSecondary = Color(0xFF283141)
internal val darkSecondaryContainer = Color(0xFF3E4759)
internal val darkOnSecondaryContainer = Color(0xFFDAE2F9)
internal val darkTertiary = Color(0xFFDDBCE0)
internal val darkOnTertiary = Color(0xFF3F2844)
internal val darkTertiaryContainer = Color(0xFF573E5C)
internal val darkOnTertiaryContainer = Color(0xFFFAD8FD)
internal val darkError = Color(0xFFFFB4AB)
internal val darkOnError = Color(0xFF690005)
internal val darkErrorContainer = Color(0xFF93000A)
internal val darkOnErrorContainer = Color(0xFFFFDAD6)
internal val darkBackground = Color(0xFF1A1C1E)
internal val darkOnBackground = Color(0xFFE2E2E6)
internal val darkSurface = Color(0xFF1A1C1E)
internal val darkOnSurface = Color(0xFFE2E2E6)
internal val darkSurfaceVariant = Color(0xFF43474E)
internal val darkOnSurfaceVariant = Color(0xFFC3C7CF)
internal val darkOutline = Color(0xFF8D9199)
